### PR TITLE
Update lodash to version 4.0.1

### PR DESCRIPTION
**Pull request by Minglee01**
@incuna/js 

Please review.

fixes
https://incuna-pm.atlassian.net/browse/AB-372
screen shot 2016-03-03 at 11 37 56

### CODE REVIEW

**Comment by wytrych** [comment]
Merge conflict?

**Comment by Minglee01** [comment]
dunno why that happened i pulled master then created this branch

**Comment by Minglee01** [comment]
@wytrych  should be good now thanks.

**Comment by henrahmagix** [comment]
Odd that the templates are now not minified. What changed there?

**Pull request merged**
